app/database/models.py
from datetime import datetime

from flask_login import UserMixin

from . import db


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    creation_dt = db.Column(db.DateTime, default=datetime.utcnow())
    email = db.Column(db.String(100), nullable=False, unique=True)
    password_hash = db.Column(db.String(), nullable=False)
    role = db.Column(db.String(20), default='user')

    # gas_price_per_gal
    # min_quote_price

    def __init__(self, email, password_hash, role=None):
        self.email = email
        self.password_hash = password_hash
        self.role = 'user' if role is None else role


# class Employee(db.Model):
#     id
#     name
#     hourly_wage
#
#     user_id
#     user
#
#
# class Vehicle(db.Model):
#     id
#     make_model
#     mpg
#
#     user_id
#     user
#
#
# class Quote(db.Model):
#     id
#     description
#     amount
#
#     user_id
#     user

app/forms/__init__.py
from flask_wtf import FlaskForm
from wtforms.fields import DecimalField


class AppForm(FlaskForm):
    name = 'AppForm'
    button_text = 'Submit'

    def __init__(self, formdata, action=None, **kwargs):
        super(AppForm, self).__init__(formdata, **kwargs)

        if action:
            self.action = action


class CurrencyField(DecimalField):
    places = 2

app/forms/auth.py
from wtforms import PasswordField
from wtforms.fields.html5 import EmailField
from wtforms.validators import DataRequired, EqualTo, Length, Email

from app.forms import AppForm

password_validators = [
    DataRequired(),
    Length(min=6, message='Password must be at least 6 characters')
]


class LoginForm(AppForm):
    name = 'Login'

    email = EmailField(
        'Email',
        validators=[
            Email(message='Invalid email address')
        ],
        description='someone@example.com'
    )

    password = PasswordField(
        'Password',
        validators=[
            DataRequired()
        ],
        description='******'
    )


class RegistrationForm(LoginForm):
    name = 'Register'

    confirm_password = PasswordField(
        'Confirm Password',
        validators=[
            *password_validators,
            EqualTo('password', message='Passwords do not match'),
        ],
        description='******'
    )

app/forms/quote.py
from wtforms.fields import DecimalField, TextAreaField

from app.forms import AppForm, CurrencyField


class WorkForm(AppForm):
    name = 'Work'
    button_text = 'Save Quote'

    description = TextAreaField(
        'Description'
    )

    hours = DecimalField(
        'Estimated Hours',
        description='Hours to complete the job',
        places=2,
        default=1.0
    )

    # manual OR sum of employee hourly_rate
    hourly_rate = CurrencyField(
        'Hourly Rate',
        description='Enter hourly rate or select from employees',
        default=0.0
    )

    # hours * sum_hourly_rate
    labor = CurrencyField(
        'Labor',
        default=0.0,
    )

    supplies = CurrencyField(
        'Parts/Supplies',
        default=0.0
    )

    misc = CurrencyField(
        'Misc',
        default=0.0
    )

    profit = CurrencyField(
        'Profit',
        default=0.0
    )

    profit_margin = DecimalField(
        'Profit Margin',
        description='Calculate profit based on the expenses amount',
        places=2,
        default=10.0,
    )

    estimate_minimum = CurrencyField(
        'Estimate Minimum',
        default=0.0
    )

    tax_rate = DecimalField(
        'Tax Rate',
        default=7.25
    )

app/__init__.py
from datetime import datetime
import os

from flask import Flask, request, render_template, jsonify
from werkzeug.exceptions import HTTPException

from app import database, routes, brand
from app.helpers import user_manager


def create_app():
    app = Flask(__name__)

    app.config.from_mapping(
        SECRET_KEY=os.environ.get('SECRET_KEY', 'dev'),
        SQLALCHEMY_DATABASE_URI=os.environ.get('SQLALCHEMY_DATABASE_URI', 'sqlite:///./database/app.db'),
        SQLALCHEMY_TRACK_MODIFICATIONS=False
    )

    # flask_login initialization
    user_manager.init_app(app)

    # database initialization
    database.init_app(app)

    routes.register_blueprints(app)
    app.add_url_rule('/', 'index')

    app.jinja_env.add_extension('jinja2.ext.do')

    @app.template_filter()
    def currency_float(value):
        return "{:,.2f}".format(value)

    @app.context_processor
    def inject_context():
        return dict(year=datetime.utcnow().year, brand=brand)

    @app.errorhandler(HTTPException)
    def unauthorized_error(error: HTTPException):
        if request.path.startswith('/api'):
            return jsonify(
                dict(message=error.name, description=error.description, status=error.code)
            ), error.code

        return render_template('error.html', error=error), error.code

    return app

app/database/__init__.py
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


def init_app(app):
    db.init_app(app)
    Migrate(app, db)

    with app.app_context():
        db.create_all()

app/routes/__init__.py
def register_blueprints(app):
    from . import index
    app.register_blueprint(index.bp)

    from . import auth
    app.register_blueprint(auth.bp)

    from . import admin
    app.register_blueprint(admin.bp)

    from . import api
    api.register_blueprints(app)

app/routes/admin.py
import itertools

from flask import Blueprint, render_template, redirect, url_for, flash
from werkzeug.exceptions import abort

from app.data_access.user import get_users, get_user_by_id, remove_user
from app.helpers.user_manager import role_required, Roles

bp = Blueprint('admin', __name__, url_prefix='/admin')


@bp.get('/')
@role_required(Roles.ADMIN)
def index():
    users = get_users(order='role')

    return render_template(
        'admin.html',
        users=users
    )


@bp.post('/users/<int:id>/delete')
@role_required(Roles.ADMIN)
def delete_user(id):
    user = get_user_by_id(id)

    if user is None:
        abort(404)

    remove_user(user)
    flash('User deleted')

    return redirect(url_for('admin.index'))

app/routes/api/__init__.py
from flask import Blueprint

api_bp = Blueprint('api', __name__, url_prefix='/api')


def register_blueprints(app):
    # registration of child blueprints within the API

    from . import user
    api_bp.register_blueprint(user.bp)

    # register the api blueprint
    app.register_blueprint(api_bp)

app/routes/auth.py
from flask import Blueprint, request, render_template, redirect, url_for, flash
from flask_login import login_user, login_required, logout_user

from app.data_access.user import add_user, get_user_by_credentials, get_user_by_email
from app.forms.auth import RegistrationForm, LoginForm
from app.helpers.user_manager import get_unauthorized_redirect

bp = Blueprint('auth', __name__)


@bp.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm(request.form)

    if request.method == 'POST' and form.validate():
        email = form.email.data

        if get_user_by_email(email):
            flash('Email already registered')

        else:
            # create and login user
            user = add_user(email, form.password.data)
            login_user(user)

            return redirect(url_for('index'))

    return render_template('auth.html', form=form)


@bp.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)

    if request.method == 'POST' and form.validate():
        user = get_user_by_credentials(form.email.data, form.password.data)

        if user is not None:
            login_user(user)

            # if the user was redirected to the login page (on account of @login_required),
            # we want to redirect the user back there
            redirect_path = get_unauthorized_redirect()

            return redirect(url_for('index') if redirect_path is None else redirect_path)

        flash('Invalid email or password')

    return render_template('auth.html', form=form)


@bp.get('/logout')
@login_required
def logout():
    logout_user()

    return redirect(url_for('index'))

app/routes/index.py
from flask import Blueprint, render_template, request
from flask_login import login_required

from app.forms.quote import WorkForm

bp = Blueprint('main', __name__)

employees = [
    {
        'name': 'Austin Malmberg',
        'hourly_rate': 20.0
    },
    {
        'name': 'Annie Sorensen',
        'hourly_rate': 42.0
    },
    {
        'name': 'Carson King',
        'hourly_rate': 20.0
    },
]


@bp.route('/', methods=['GET', 'POST'])
def index():
    form = WorkForm(request.form, action=request.path)

    return render_template('quote.html', form=form, employees=employees)


@bp.route('/dashboard')
@login_required
def dashboard():
    return render_template('dashboard.html')

app/templates/admin.html
{% extends 'layouts/base.html' %}

{% block content %}
<div class="container">
    <h1>{% block title %}Users{% endblock %}</h1>
    {% with messages = get_flashed_messages() %}
        {% if messages %}
        <div class="alert alert-info">
            <ul class="list-unstyled mb-0">
                {% for message in messages %}
                <li>{{ message }}</li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}
    {% endwith %}
    <table class="table table-striped border">
        <thead>
        <tr>
            <th scope="col">Email</th>
            <th scope="col">Role</th>
            <th scope="col">Action</th>
        </tr>
        </thead>
        <tbody>
        {% for user in users %}
        <tr>
            <th scope="row">{{ user.email }}</th>
            <td>{{ user.role }}</td>
            <td>
                {% if user.role != 'admin' %}
                <form action="{{ url_for('admin.delete_user', id=user.id) }}" method="post">
                    <button class="btn btn-primary btn-sm" type="submit">Delete</button>
                </form>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

app/templates/auth.html
{% extends 'layouts/base.html' %}

{% from 'components/_forms.html' import inline_form %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{% block title %}{{ form.name }}{% endblock %}</div>
                <div class="card-body">
                    {% set server_errors = get_flashed_messages() %}
                    {% if form.errors or server_errors %}
                    <div class="alert alert-danger">
                        <ul class="list-unstyled mb-0">
                            {% if form.errors %}
                                {% for _, field_errors in form.errors.items() %}
                                    {% for error in field_errors %}
                                    <li>{{ error }}</li>
                                    {% endfor %}
                                {% endfor %}
                            {% endif %}

                            {% if server_errors %}
                                {% for message in server_errors %}
                                <li>{{ message }}</li>
                                {% endfor %}
                            {% endif %}
                        </ul>
                    </div>
                    {% endif %}

                    {{ inline_form(form) }}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/components/_forms.html
{% from 'components/_utils.html' import surround %}

{% macro inline_form(form) %}
<form action="{{ form.action or request.path }}" method="post">
    {% for field in form %}
    {% if field.widget.input_type == 'hidden' -%}
        {{ field }}
    {% else %}
        <div class="mb-4 row align-items-center">
            {% if field.type == 'BooleanField' -%}
                {{ field(class='form-control offset-md-4') }} {{ field.label(class='col-form-label col-md-6') }}
            {% else -%}
                {{ field.label(class='col-md-4 col-form-label text-md-end') }}
                <div class="col-md-6">
                    {{ field(class='form-control', placeholder=field.description) }}
                </div>
            {%- endif %}
        </div>
    {% endif %}
    {% endfor %}

    <button type="submit" class="btn btn-primary col col-md-3 offset-md-7">{{ form.button_text or form.name }}</button>
</form>
{% endmacro %}

app/templates/components/_utils.html
{% macro surround(content='', prefix='', suffix='') %}
    {%- if prefix -%}
        {{ prefix }}&nbsp;
    {%- endif -%}

    {%- if content -%}
        {{ content }}
    {% else %}
        {{ caller() }}
    {% endif %}

    {%- if suffix -%}
        &nbsp;{{ suffix }}
    {%- endif -%}
{% endmacro %}

app/templates/dashboard.html
{% extends 'layouts/base.html' %}

{% block content %}

<div class="container">
    <h1>{% block title %}Dashboard{% endblock %}</h1>

    <p>Logged in as {{ current_user.email }}.</p>
</div>

{% endblock %}

app/templates/error.html
{% extends 'layouts/base.html' %}

{% block content %}
<div class="container">
    <h1>{% block title %}{{ error.name }}{% endblock %}</h1>
    <p>{{ error.description }}</p>
</div>
{% endblock %}

app/templates/layouts/_footer.html
<footer class="my-3">
    <div class="container">
        <p class="text-center text-muted">&copy; {{ year }} {{ brand.company }}</p>
    </div>
</footer>

app/templates/layouts/_navbar.html
<div class="navbar navbar-expand-md navbar-light bg-light mb-4">
    <div class="container">
        <a href="{{ url_for('index') }}" class="navbar-brand">{{ brand.name }}</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-md-auto">
                {% if current_user.is_authenticated %}
                    {% if current_user.role == 'admin' %}
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('admin.index') }}">Admin</a></li>
                    {% endif %}
                <li class="nav-item"><a class="nav-link" href="{{ url_for('main.dashboard') }}">Dashboard</a></li>
                <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a></li>
                {% else %}
                <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.register') }}">Register</a></li>
                <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.login') }}">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>

app/templates/layouts/base.html
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/bootswatch_flatly.min.css') }}">

        <!-- Bootstrap 5
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
            crossorigin="anonymous">
        -->
        <link href="{{ url_for('static', filename='styles/style.css') }}" rel="stylesheet">
        <title>{% block title %}{% endblock %} | {{ brand.name }}</title>

        {% block head %}{% endblock %}
    </head>

    <body>
        <main role="main" style="min-height:100vh;" class="d-flex flex-column">
            <header>
                {% include 'layouts/_navbar.html' %}
            </header>

            <div class="flex-grow-1">
                {% block content %}{% endblock %}
            </div>

            {% include 'layouts/_footer.html' %}
        </main>

        <!-- Bootstrap scripts -->
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
            integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
            crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js"
            integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT"
            crossorigin="anonymous"></script>

        {% block scripts %}{% endblock %}

    </body>
</html>

app/templates/quote.html
{% extends 'layouts/base.html' %}

{% from 'components/_utils.html' import surround %}

{% macro main_div(underlined=True) %}
<div class="row align-items-center py-2 mb-3{{ ' border-bottom' if underlined else '' }}">
    {{ caller() }}
</div>
{% endmacro %}

{% macro input_div() %}
<div class="col-4 col-md-3 d-flex align-items-center">
    {{ caller() }}
</div>
{% endmacro %}

{% macro h2_field(field, input_attrs=dict(), label_attrs=dict(), input_prefix='', input_suffix='') %}
{% call main_div() %}
    {% do label_attrs.update({'class': ' '.join(['w-100', label_attrs.class or '']) }) %}
    <h2 class="col-8 col-md-9">{{ field.label(**label_attrs) }}</h2>
    {% call input_div() %}
        {% set input_prefix = '$' if not input_prefix and field.type == 'CurrencyField' else '' %}
        {% call surround(prefix=input_prefix, suffix=input_suffix) %}
            {% do input_attrs.update({'class': ' '.join(['form-control text-center', input_attrs.class or '']) }) %}
            {{ field(**input_attrs) }}
        {% endcall %}
    {% endcall %}
{% endcall %}
{% endmacro %}

{% macro sub_div() %}
<div class="row align-items-center pb-1 my-1">
    {{ caller() }}
</div>
{% endmacro %}

{% macro h3_field(field, input_attrs=dict(), label_attrs=dict(), input_prefix='', input_suffix='') %}
{% do input_attrs.update({'class': ' '.join(['form-control', input_attrs.class or '']) }) %}
{% call sub_div() %}
    {% if field.type == 'TextAreaField' %}
        {% do input_attrs.update({'class': ' '.join(['w-100', input_attrs.class or '']) }) %}
        <div class="my-2">
            <h3 class="h4 {{ 'mb-0' if field.description else '' }}">{{ field.label(**label_attrs) }}</h3>
            {% if field.description %}
            <span class="text-muted">{{ field.description }}</span>
            {% endif %}
        </div>
        <div>
            {{ field(**input_attrs) }}
        </div>
    {% else %}
        <div class="col-8 col-md-9 my-2 {{ 'd-flex flex-column' if field.description else '' }}">
            <h3 class="h4 {{ 'mb-0' if field.description else '' }}">{{ field.label(**label_attrs) }}</h3>
            {% if field.description %}
            <span class="text-muted">{{ field.description }}</span>
            {% endif %}
        </div>
        {% call input_div() %}
            {% set input_prefix = '$' if not input_prefix and field.type == 'CurrencyField' else '' %}
            {% do input_attrs.update({'class': ' '.join(['text-center', input_attrs.class or '']) }) %}
            {% call surround(prefix=input_prefix, suffix=input_suffix) %}
                {{ field(**input_attrs) }}
            {% endcall %}
        {% endcall %}
    {% endif %}
{% endcall %}
{% endmacro %}

{% macro h3_container() %}
<div class="px-lg-3 mx-lg-2">
    {{ caller() }}
</div>
{% endmacro %}

{% block title %}Home{% endblock %}

{% macro total_row(title, value='', underlined=True, data_calc='', subscribers='') %}
{% call main_div(underlined=underlined) %}
<h2 class="col-8 col-md-9">{{ title }}</h2>
<div class="h4 fw-bold col-4 col-md-3 text-center">
    {% call surround(prefix='$') %}
    <span
            id="{{ title|replace(' ', '-')|lower }}"
            {% if data_calc %}data-calc="{{ data_calc }}"{% endif %}
            {% if subscribers %}data-calc-subscribers="{{ subscribers }}"{% endif %}
    >{{ value }}</span>
    {% endcall %}
</div>
{% endcall %}
{% endmacro %}

{% macro employee_card(employee, is_active=False) %}
{% set active_classes = 'active bg-dark text-white' %}
<div class="col-6 col-md-4 my-2">
    <div class="employee card border-rounded hover-grow {{ active_classes if is_active else '' }}" data-toggle="{{ active_classes }}">
        <div class="card-body">
            <h5 class="card-title">{{ employee.name }}</h5>
            <p class="card-text" data-rate="{{ employee.hourly_rate }}">
                <span class="text-muted">Hourly rate:</span>
                <span class="rate" data-value="{{ employee.hourly_rate }}">${{ employee.hourly_rate|currency_float }}</span>
            </p>
        </div>
    </div>
</div>
{% endmacro %}

{% block content %}
<div class="container col-lg-8 px-2">
    <h1 class="text-center">Estimate</h1>
    <form action="{{ form.action }}" method="post">
        {% call main_div() %}
            <h2>Job Details</h2>
        {% endcall %}
        {% call h3_container() %}
            {{ h3_field(form.description) }}
            {{ h3_field(form.hours) }}
            {{ h3_field(form.hourly_rate) }}
            <div id="employees" class="row my-2 py-2">
            {% for employee in employees %}
                {{ employee_card(employee, loop.first) }}
            {% endfor %}
            </div>
        {% endcall %}

        {{ total_row('Expenses', value='0.00', data_calc='#supplies + #misc') }}
        {% call h3_container() %}
            {{ h3_field(form.labor, input_attrs=dict(class='expense', data_calc='#hourly_rate * #hours')) }}
            {{ h3_field(form.supplies, input_attrs=dict(class='expense')) }}
            {{ h3_field(form.misc, input_attrs=dict(class='expense')) }}
        {% endcall %}

        {{ h2_field(form.profit, input_attrs=dict(class='fw-bold border-light', style='font-size:calc(1.275rem + .3vw)', data_calc='#subtotal * #profit_margin / 100')) }}
        {% call h3_container() %}
            {{ h3_field(form.profit_margin, input_suffix='%') }}
        {% endcall %}

        {{ total_row('Subtotal', value='0.00', data_calc='#expenses + #profit', subscribers='grand-total') }}

        {{ total_row('Tax', value='0.00', data_calc='#subtotal * #tax_rate / 100') }}
        {% call h3_container() %}
            {{ h3_field(form.tax_rate, input_suffix='%') }}
        {% endcall %}

        {{ total_row(title='Grand Total', value='0.00', data_calc='#subtotal + #tax', underlined=False) }}

        <div class="row mt-4 mb-2">
            <button type="submit" class="btn btn-primary btn-lg col-6 offset-6 col-md-4 offset-md-8">{{ form.button_text }}</button>
        </div>
    </form>
</div>
{% endblock %}

{% block scripts %}
<script type="text/javascript">
    const toggleElements = document.querySelectorAll("[data-toggle]")
    for (const toggle of toggleElements) {
        toggleClasses = toggle.getAttribute('data-toggle').split(" ");
        toggle.addEventListener('click', (event) => toggleClasses.forEach(cls => toggle.classList.toggle(cls)));
    }
</script>
<script type="text/javascript" src="{{ url_for('static', filename='scripts/estimate.js') }}"></script>
{% endblock %}